version: "3.3"

services:
  users_mng_svc:
    image: users_mng_service
    container_name: users_mng_svc
    build:
      context: ./../
      dockerfile: infra/Dockerfile
    env_file:
      - .env.dev
    restart: on-failure
    ports:
      - "50000:50000"
      - "4000:4000"
    networks:
      - user_mng
    depends_on:
      - users_db
      - kafka

  users_db:
    image: postgres:14.4-alpine
    container_name: users_db
    hostname: users_db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: users_db
    networks:
      - user_mng

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - user_mng
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - user_mng

networks:
  user_mng: